# Generated by Django 2.2.1 on 2019-05-05 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gameBar', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Todo',
            new_name='GameBar',
        ),
    ]
