# Generated by Django 2.2.1 on 2019-05-08 04:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gameBar', '0002_auto_20190505_2149'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('address', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('opened', models.DateTimeField()),
                ('closed', models.DateTimeField()),
                ('bar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='gameBar.Bar')),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('value', models.FloatField()),
                ('status', models.BooleanField(default=True)),
                ('bar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='gameBar.Bar')),
            ],
        ),
        migrations.DeleteModel(
            name='GameBar',
        ),
        migrations.AddField(
            model_name='game',
            name='participantA',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='participantA', to='gameBar.Participant'),
        ),
        migrations.AddField(
            model_name='game',
            name='participantB',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='participantB', to='gameBar.Participant'),
        ),
        migrations.AddField(
            model_name='game',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gameBar.Product'),
        ),
        migrations.AddField(
            model_name='game',
            name='winner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='winner', to='gameBar.Participant'),
        ),
    ]
