# Generated by Django 2.2.1 on 2019-05-12 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameBar', '0004_auto_20190512_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='closed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
