# Generated by Django 2.2.1 on 2019-05-12 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameBar', '0005_auto_20190512_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bar',
            name='status',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='status',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
